"""p2-add-appconfig-userfavorite-announcement

Revision ID: fd8202321cd1
Revises: 65a7e09c9884
Create Date: 2026-06-27 11:37:16.127857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd8202321cd1'
down_revision: Union[str, Sequence[str], None] = '65a7e09c9884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='优先级（1高2中3低）'),
    sa.Column('publish_at', sa.DateTime(), nullable=True, comment='定时发布时间'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（0草稿1发布2撤下）'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='发布人ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统公告',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('app_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('config_key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置说明'),
    sa.Column('group_name', sa.String(length=64), nullable=True, comment='分组名称'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后修改人ID'),
    sa.Column('is_sensitive', sa.SmallInteger(), nullable=False, comment='是否敏感配置（0否1是）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（1启用0禁用）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    comment='系统配置（key-value）',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('user_favorite',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='消息ID（关联QA消息）'),
    sa.Column('note', sa.Text(), nullable=True, comment='用户备注'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态（1启用0删除）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='收藏时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户收藏',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_favorite_message_id'), 'user_favorite', ['message_id'], unique=False)
    op.create_index(op.f('ix_user_favorite_user_id'), 'user_favorite', ['user_id'], unique=False)
    op.drop_index(op.f('uk_embedding_cache_key'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    op.alter_column('agent_refusal_log', 'query',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_comment='被拒答的用户问题',
               existing_nullable=False)
    op.drop_index(op.f('idx_agent_refusal_created'), table_name='agent_refusal_log')
    op.drop_index(op.f('idx_citation_quality_message'), table_name='citation_quality_log')
    op.drop_index(op.f('idx_consistency_message'), table_name='consistency_issue_log')
    op.drop_index(op.f('idx_fact_verify_message'), table_name='fact_verification_log')
    op.alter_column('kb_category', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='分类ID',
               existing_comment='分类ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('kb_category', 'parent_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='父分类ID,0为顶级',
               existing_comment='父分类ID，0为顶级',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_category', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment='分类名称',
               existing_comment='分类名称，如 就业政策/办事流程/招聘信息',
               existing_nullable=False)
    op.alter_column('kb_category', 'sort',
               existing_type=mysql.INTEGER(),
               comment='排序值,越小越靠前',
               existing_comment='排序值，越小越靠前',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_parent_id'), table_name='kb_category')
    op.create_index(op.f('ix_kb_category_parent_id'), 'kb_category', ['parent_id'], unique=False)
    op.alter_column('kb_document', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='文档ID',
               existing_comment='文档ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('kb_document', 'source',
               existing_type=mysql.VARCHAR(length=255),
               comment='来源(发文机关/网站)',
               existing_comment='来源(发文机关/网站/上传人备注)',
               existing_nullable=True)
    op.alter_column('kb_document', 'source_level',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='政策层级1国2省3市4校',
               existing_comment='政策层级：1国家 2省 3市 4校级',
               existing_nullable=True)
    op.alter_column('kb_document', 'file_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='pdf/docx/xlsx/txt/html',
               existing_comment='文件类型：pdf/docx/xlsx/txt/html',
               existing_nullable=True)
    op.alter_column('kb_document', 'file_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment='内容哈希SHA-256,去重',
               existing_comment='文件内容哈希(SHA-256)，用于去重',
               existing_nullable=True)
    op.alter_column('kb_document', 'effective_date',
               existing_type=sa.DATE(),
               comment='生效日期',
               existing_comment='生效日期(用于过滤时效)',
               existing_nullable=True)
    op.alter_column('kb_document', 'expire_date',
               existing_type=sa.DATE(),
               comment='失效日期,空为长期有效',
               existing_comment='失效日期，为空表示长期有效',
               existing_nullable=True)
    op.alter_column('kb_document', 'confidential_level',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='密级1公开2校内3受限',
               existing_comment='密级：1公开 2校内 3受限',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('kb_document', 'parse_status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='0待解析1解析中2成功3失败',
               existing_comment='解析状态：0待解析 1解析中 2成功 3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_document', 'index_status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='0未索引1索引中2已索引3失败',
               existing_comment='索引状态：0未索引 1索引中 2已索引 3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_document', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1上架可检索0下架',
               existing_comment='上架状态：1启用(可检索) 0下架',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_category_id'), table_name='kb_document')
    op.drop_index(op.f('idx_effective_date'), table_name='kb_document')
    op.drop_index(op.f('idx_file_hash'), table_name='kb_document')
    op.drop_index(op.f('idx_index_status'), table_name='kb_document')
    op.drop_index(op.f('idx_status'), table_name='kb_document')
    op.create_index(op.f('ix_kb_document_category_id'), 'kb_document', ['category_id'], unique=False)
    op.create_index(op.f('ix_kb_document_effective_date'), 'kb_document', ['effective_date'], unique=False)
    op.create_index(op.f('ix_kb_document_file_hash'), 'kb_document', ['file_hash'], unique=False)
    op.create_index(op.f('ix_kb_document_index_status'), 'kb_document', ['index_status'], unique=False)
    op.create_index(op.f('ix_kb_document_status'), 'kb_document', ['status'], unique=False)
    op.alter_column('kb_document_chunk', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='分片ID',
               existing_comment='分片ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('kb_document_chunk', 'chunk_index',
               existing_type=mysql.INTEGER(),
               comment='分片序号(从0开始)',
               existing_comment='分片在文档内的序号(从0开始)',
               existing_nullable=False)
    op.alter_column('kb_document_chunk', 'heading_path',
               existing_type=mysql.VARCHAR(length=512),
               comment='标题层级路径',
               existing_comment='所属标题层级路径，如 第一章>第三条',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'page_no',
               existing_type=mysql.INTEGER(),
               comment='原文页码(溯源)',
               existing_comment='原文页码(便于溯源)',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'vector_id',
               existing_type=mysql.VARCHAR(length=128),
               comment='向量库中的向量ID',
               existing_comment='向量库中的向量ID(外部引用)',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'embedding',
               existing_type=mysql.JSON(),
               comment='向量备份(小规模可选)',
               existing_comment='向量备份(小规模可选存储,大规模留空)',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'embedding_model',
               existing_type=mysql.VARCHAR(length=64),
               comment='生成向量的模型名',
               existing_comment='生成向量所用模型名',
               existing_nullable=True)
    op.drop_index(op.f('ft_content'), table_name='kb_document_chunk', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.drop_index(op.f('idx_vector_id'), table_name='kb_document_chunk')
    op.drop_index(op.f('uk_doc_chunk'), table_name='kb_document_chunk')
    op.create_index(op.f('ix_kb_document_chunk_document_id'), 'kb_document_chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_kb_document_chunk_vector_id'), 'kb_document_chunk', ['vector_id'], unique=False)
    op.create_table_comment(
        'kb_document_chunk',
        '文档分片表：切分文本块,含关键词全文索引',
        existing_comment='文档分片表：切分后的文本块，含全文索引(ngram)支持关键词检索',
        schema=None
    )
    op.alter_column('kb_faq', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='FAQ ID',
               existing_comment='FAQ ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('kb_faq', 'vector_id',
               existing_type=mysql.VARCHAR(length=128),
               comment='问题向量ID',
               existing_comment='问题向量ID(用于相似问匹配)',
               existing_nullable=True)
    op.alter_column('kb_faq', 'hit_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='命中次数(热度)',
               existing_comment='命中次数(热度统计)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_faq', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1启用0禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ft_question'), table_name='kb_faq', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.drop_index(op.f('idx_category_id'), table_name='kb_faq')
    op.create_index(op.f('ix_kb_faq_category_id'), 'kb_faq', ['category_id'], unique=False)
    op.create_table_comment(
        'kb_faq',
        'FAQ问答对表',
        existing_comment='FAQ问答对表：高频问题的标准答复',
        schema=None
    )
    op.drop_index(op.f('uk_kb_health_check_date'), table_name='kb_health_log')
    op.alter_column('kb_index_task', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='任务ID',
               existing_comment='任务ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('kb_index_task', 'task_type',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1解析2入库3重建4删除索引',
               existing_comment='任务类型：1解析 2向量化入库 3重建 4删除索引',
               existing_nullable=False)
    op.alter_column('kb_index_task', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='0排队1执行中2成功3失败',
               existing_comment='状态：0排队 1执行中 2成功 3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_index_task', 'progress',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='进度百分比0-100',
               existing_comment='进度百分比 0-100',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_document_id'), table_name='kb_index_task')
    op.drop_index(op.f('idx_status'), table_name='kb_index_task')
    op.create_index(op.f('ix_kb_index_task_document_id'), 'kb_index_task', ['document_id'], unique=False)
    op.create_index(op.f('ix_kb_index_task_status'), 'kb_index_task', ['status'], unique=False)
    op.create_table_comment(
        'kb_index_task',
        '索引任务表：文档解析/入库任务监控',
        existing_comment='索引任务表：文档解析/入库异步任务监控',
        schema=None
    )
    op.alter_column('kb_synonym', 'term',
               existing_type=mysql.VARCHAR(length=128),
               comment='标准词',
               existing_comment='标准词，如 三方协议',
               existing_nullable=False)
    op.alter_column('kb_synonym', 'synonyms',
               existing_type=mysql.VARCHAR(length=512),
               comment='同义词,逗号分隔',
               existing_comment='同义词/别名，逗号分隔，如 三方,就业协议书',
               existing_nullable=False)
    op.alter_column('kb_synonym', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1启用0禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_term'), table_name='kb_synonym')
    op.create_index(op.f('ix_kb_synonym_term'), 'kb_synonym', ['term'], unique=False)
    op.create_table_comment(
        'kb_synonym',
        '同义词词典表：提升召回',
        existing_comment='同义词词典表：校内黑话/专有名词映射，提升召回',
        schema=None
    )
    op.drop_index(op.f('uk_llm_cost_date_model'), table_name='llm_cost_log')
    op.alter_column('op_eval_case', 'expected_doc_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='期望命中文档ID',
               existing_comment='期望命中的文档ID',
               existing_nullable=True)
    op.alter_column('op_eval_case', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1启用0禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_table_comment(
        'op_eval_case',
        '评测集表：质量回归',
        existing_comment='评测集表：用于回归测试准确率/召回率',
        schema=None
    )
    op.alter_column('op_query_log', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='日志ID',
               existing_comment='日志ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('op_query_log', 'is_no_answer',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='是否无答案1是0否',
               existing_comment='是否无答案：1是 0否',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('op_query_log', 'channel',
               existing_type=mysql.VARCHAR(length=32),
               comment='来源渠道web/h5/wecom',
               existing_comment='来源渠道：web/h5/wecom',
               existing_nullable=True)
    op.drop_index(op.f('idx_created_at'), table_name='op_query_log')
    op.drop_index(op.f('idx_no_answer'), table_name='op_query_log')
    op.drop_index(op.f('idx_user_id'), table_name='op_query_log')
    op.create_index(op.f('ix_op_query_log_created_at'), 'op_query_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_query_log_is_no_answer'), 'op_query_log', ['is_no_answer'], unique=False)
    op.create_index(op.f('ix_op_query_log_user_id'), 'op_query_log', ['user_id'], unique=False)
    op.create_table_comment(
        'op_query_log',
        '问答日志表：审计与统计',
        existing_comment='问答日志表：全量问答审计与统计分析',
        schema=None
    )
    op.alter_column('op_sensitive_word', 'category',
               existing_type=mysql.VARCHAR(length=64),
               comment='分类',
               existing_comment='分类：政治/色情/无关等',
               existing_nullable=True)
    op.alter_column('op_sensitive_word', 'action',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1拦截2替换3告警',
               existing_comment='处理方式：1拦截 2替换 3告警',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('op_sensitive_word', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1启用0禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.create_table_comment(
        'op_sensitive_word',
        '敏感词表：合规过滤',
        existing_comment='敏感词表：提问内容合规过滤',
        schema=None
    )
    op.alter_column('qa_conversation', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='会话ID',
               existing_comment='会话ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('qa_conversation', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属用户ID(匿名可空)',
               existing_comment='所属用户ID(匿名可为空)',
               existing_nullable=True)
    op.alter_column('qa_conversation', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1正常0已删除',
               existing_comment='状态：1正常 0已删除',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_user_id'), table_name='qa_conversation')
    op.create_index(op.f('ix_qa_conversation_user_id'), 'qa_conversation', ['user_id'], unique=False)
    op.alter_column('qa_feedback', 'rating',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1点赞-1点踩',
               existing_comment='评价：1点赞 -1点踩',
               existing_nullable=False)
    op.alter_column('qa_feedback', 'reason',
               existing_type=mysql.VARCHAR(length=512),
               comment='点踩原因/补充',
               existing_comment='点踩原因/补充说明',
               existing_nullable=True)
    op.drop_index(op.f('uk_msg_user'), table_name='qa_feedback')
    op.create_index(op.f('ix_qa_feedback_message_id'), 'qa_feedback', ['message_id'], unique=False)
    op.create_table_comment(
        'qa_feedback',
        '答案反馈表：点赞/点踩',
        existing_comment='答案反馈表：用户点赞/点踩，回流优化',
        schema=None
    )
    op.alter_column('qa_message', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='消息ID',
               existing_comment='消息ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('qa_message', 'role',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1用户提问2系统回答',
               existing_comment='角色：1用户提问 2系统回答',
               existing_nullable=False)
    op.alter_column('qa_message', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               comment='消息内容',
               existing_comment='消息内容(问题或答案)',
               existing_nullable=False)
    op.alter_column('qa_message', 'rewritten_query',
               existing_type=mysql.VARCHAR(length=1024),
               comment='查询改写后的问题',
               existing_comment='查询改写后的问题(仅提问消息)',
               existing_nullable=True)
    op.alter_column('qa_message', 'answer_type',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1知识库生成2FAQ命中3无答案兜底',
               existing_comment='答案类型：1知识库生成 2FAQ命中 3无答案兜底(仅回答消息)',
               existing_nullable=True)
    op.alter_column('qa_message', 'is_no_answer',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='是否兜底无答案1是0否',
               existing_comment='是否兜底无答案：1是 0否',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qa_message', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='综合置信度(0-1)',
               existing_comment='综合置信度',
               existing_nullable=True)
    op.alter_column('qa_message', 'query_risk_level',
               existing_type=mysql.VARCHAR(length=20),
               comment='查询风险等级(high/medium/low)',
               existing_comment='查询风险等级 high/medium/low',
               existing_nullable=True)
    op.alter_column('qa_message', 'consistency_issues',
               existing_type=mysql.JSON(),
               comment='一致性问题列表(JSON)',
               existing_comment='自我一致性检查问题列表(JSON)',
               existing_nullable=True)
    op.drop_index(op.f('idx_conversation_id'), table_name='qa_message')
    op.drop_index(op.f('idx_created_at'), table_name='qa_message')
    op.create_index(op.f('ix_qa_message_conversation_id'), 'qa_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_qa_message_created_at'), 'qa_message', ['created_at'], unique=False)
    op.create_table_comment(
        'qa_message',
        '消息表：每条提问/回答',
        existing_comment='消息表：对话中的每条提问/回答',
        schema=None
    )
    op.alter_column('qa_message_reference', 'rank_no',
               existing_type=mysql.INTEGER(),
               comment='引用排序',
               existing_comment='在引用中的排序',
               existing_nullable=True)
    op.alter_column('qa_message_reference', 'snippet',
               existing_type=mysql.TEXT(),
               comment='引用片段摘要',
               existing_comment='引用片段摘要(用于展示)',
               existing_nullable=True)
    op.drop_index(op.f('idx_document_id'), table_name='qa_message_reference')
    op.drop_index(op.f('idx_message_id'), table_name='qa_message_reference')
    op.create_index(op.f('ix_qa_message_reference_document_id'), 'qa_message_reference', ['document_id'], unique=False)
    op.create_index(op.f('ix_qa_message_reference_message_id'), 'qa_message_reference', ['message_id'], unique=False)
    op.create_table_comment(
        'qa_message_reference',
        '答案引用来源表：记录命中分片,支持溯源',
        existing_comment='答案引用来源表：记录每条答案命中的文档分片，支持溯源',
        schema=None
    )
    op.alter_column('sys_role', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='角色ID',
               existing_comment='角色ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_role', 'role_code',
               existing_type=mysql.VARCHAR(length=64),
               comment='角色编码 admin/editor/student',
               existing_comment='角色编码，如 admin/editor/student',
               existing_nullable=False)
    op.create_table_comment(
        'sys_role',
        '角色表：后台权限控制(RBAC)',
        existing_comment='角色表：用于后台权限控制(RBAC)',
        schema=None
    )
    op.alter_column('sys_user', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_comment='用户ID，主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码哈希',
               existing_comment='密码哈希(统一身份认证用户可为空)',
               existing_nullable=True)
    op.alter_column('sys_user', 'user_type',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1学生2毕业生3辅导员4老师5管理员',
               existing_comment='用户类型：1学生 2毕业生 3辅导员 4就业中心老师 5管理员',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               comment='手机号(展示脱敏)',
               existing_comment='手机号(展示时脱敏)',
               existing_nullable=True)
    op.alter_column('sys_user', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1启用0禁用',
               existing_comment='状态：1启用 0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('idx_user_type'), table_name='sys_user')
    op.drop_index(op.f('idx_role_id'), table_name='sys_user_role')
    op.drop_index(op.f('uk_user_role'), table_name='sys_user_role')
    op.create_index(op.f('ix_sys_user_role_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_user_id'), 'sys_user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_role_user_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_role_id'), table_name='sys_user_role')
    op.create_index(op.f('uk_user_role'), 'sys_user_role', ['user_id', 'role_id'], unique=True)
    op.create_index(op.f('idx_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('idx_user_type'), 'sys_user', ['user_type'], unique=False)
    op.alter_column('sys_user', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1启用 0禁用',
               existing_comment='1启用0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sys_user', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               comment='手机号(展示时脱敏)',
               existing_comment='手机号(展示脱敏)',
               existing_nullable=True)
    op.alter_column('sys_user', 'user_type',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='用户类型：1学生 2毕业生 3辅导员 4就业中心老师 5管理员',
               existing_comment='1学生2毕业生3辅导员4老师5管理员',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sys_user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码哈希(统一身份认证用户可为空)',
               existing_comment='密码哈希',
               existing_nullable=True)
    op.alter_column('sys_user', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID，主键',
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'sys_role',
        '角色表：用于后台权限控制(RBAC)',
        existing_comment='角色表：后台权限控制(RBAC)',
        schema=None
    )
    op.alter_column('sys_role', 'role_code',
               existing_type=mysql.VARCHAR(length=64),
               comment='角色编码，如 admin/editor/student',
               existing_comment='角色编码 admin/editor/student',
               existing_nullable=False)
    op.alter_column('sys_role', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='角色ID，主键',
               existing_comment='角色ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'qa_message_reference',
        '答案引用来源表：记录每条答案命中的文档分片，支持溯源',
        existing_comment='答案引用来源表：记录命中分片,支持溯源',
        schema=None
    )
    op.drop_index(op.f('ix_qa_message_reference_message_id'), table_name='qa_message_reference')
    op.drop_index(op.f('ix_qa_message_reference_document_id'), table_name='qa_message_reference')
    op.create_index(op.f('idx_message_id'), 'qa_message_reference', ['message_id'], unique=False)
    op.create_index(op.f('idx_document_id'), 'qa_message_reference', ['document_id'], unique=False)
    op.alter_column('qa_message_reference', 'snippet',
               existing_type=mysql.TEXT(),
               comment='引用片段摘要(用于展示)',
               existing_comment='引用片段摘要',
               existing_nullable=True)
    op.alter_column('qa_message_reference', 'rank_no',
               existing_type=mysql.INTEGER(),
               comment='在引用中的排序',
               existing_comment='引用排序',
               existing_nullable=True)
    op.create_table_comment(
        'qa_message',
        '消息表：对话中的每条提问/回答',
        existing_comment='消息表：每条提问/回答',
        schema=None
    )
    op.drop_index(op.f('ix_qa_message_created_at'), table_name='qa_message')
    op.drop_index(op.f('ix_qa_message_conversation_id'), table_name='qa_message')
    op.create_index(op.f('idx_created_at'), 'qa_message', ['created_at'], unique=False)
    op.create_index(op.f('idx_conversation_id'), 'qa_message', ['conversation_id'], unique=False)
    op.alter_column('qa_message', 'consistency_issues',
               existing_type=mysql.JSON(),
               comment='自我一致性检查问题列表(JSON)',
               existing_comment='一致性问题列表(JSON)',
               existing_nullable=True)
    op.alter_column('qa_message', 'query_risk_level',
               existing_type=mysql.VARCHAR(length=20),
               comment='查询风险等级 high/medium/low',
               existing_comment='查询风险等级(high/medium/low)',
               existing_nullable=True)
    op.alter_column('qa_message', 'confidence',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='综合置信度',
               existing_comment='综合置信度(0-1)',
               existing_nullable=True)
    op.alter_column('qa_message', 'is_no_answer',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='是否兜底无答案：1是 0否',
               existing_comment='是否兜底无答案1是0否',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('qa_message', 'answer_type',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='答案类型：1知识库生成 2FAQ命中 3无答案兜底(仅回答消息)',
               existing_comment='1知识库生成2FAQ命中3无答案兜底',
               existing_nullable=True)
    op.alter_column('qa_message', 'rewritten_query',
               existing_type=mysql.VARCHAR(length=1024),
               comment='查询改写后的问题(仅提问消息)',
               existing_comment='查询改写后的问题',
               existing_nullable=True)
    op.alter_column('qa_message', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               comment='消息内容(问题或答案)',
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('qa_message', 'role',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='角色：1用户提问 2系统回答',
               existing_comment='1用户提问2系统回答',
               existing_nullable=False)
    op.alter_column('qa_message', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='消息ID，主键',
               existing_comment='消息ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'qa_feedback',
        '答案反馈表：用户点赞/点踩，回流优化',
        existing_comment='答案反馈表：点赞/点踩',
        schema=None
    )
    op.drop_index(op.f('ix_qa_feedback_message_id'), table_name='qa_feedback')
    op.create_index(op.f('uk_msg_user'), 'qa_feedback', ['message_id', 'user_id'], unique=True)
    op.alter_column('qa_feedback', 'reason',
               existing_type=mysql.VARCHAR(length=512),
               comment='点踩原因/补充说明',
               existing_comment='点踩原因/补充',
               existing_nullable=True)
    op.alter_column('qa_feedback', 'rating',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='评价：1点赞 -1点踩',
               existing_comment='1点赞-1点踩',
               existing_nullable=False)
    op.drop_index(op.f('ix_qa_conversation_user_id'), table_name='qa_conversation')
    op.create_index(op.f('idx_user_id'), 'qa_conversation', ['user_id'], unique=False)
    op.alter_column('qa_conversation', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1正常 0已删除',
               existing_comment='1正常0已删除',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('qa_conversation', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属用户ID(匿名可为空)',
               existing_comment='所属用户ID(匿名可空)',
               existing_nullable=True)
    op.alter_column('qa_conversation', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='会话ID，主键',
               existing_comment='会话ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'op_sensitive_word',
        '敏感词表：提问内容合规过滤',
        existing_comment='敏感词表：合规过滤',
        schema=None
    )
    op.alter_column('op_sensitive_word', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1启用 0禁用',
               existing_comment='1启用0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('op_sensitive_word', 'action',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='处理方式：1拦截 2替换 3告警',
               existing_comment='1拦截2替换3告警',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('op_sensitive_word', 'category',
               existing_type=mysql.VARCHAR(length=64),
               comment='分类：政治/色情/无关等',
               existing_comment='分类',
               existing_nullable=True)
    op.create_table_comment(
        'op_query_log',
        '问答日志表：全量问答审计与统计分析',
        existing_comment='问答日志表：审计与统计',
        schema=None
    )
    op.drop_index(op.f('ix_op_query_log_user_id'), table_name='op_query_log')
    op.drop_index(op.f('ix_op_query_log_is_no_answer'), table_name='op_query_log')
    op.drop_index(op.f('ix_op_query_log_created_at'), table_name='op_query_log')
    op.create_index(op.f('idx_user_id'), 'op_query_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_no_answer'), 'op_query_log', ['is_no_answer'], unique=False)
    op.create_index(op.f('idx_created_at'), 'op_query_log', ['created_at'], unique=False)
    op.alter_column('op_query_log', 'channel',
               existing_type=mysql.VARCHAR(length=32),
               comment='来源渠道：web/h5/wecom',
               existing_comment='来源渠道web/h5/wecom',
               existing_nullable=True)
    op.alter_column('op_query_log', 'is_no_answer',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='是否无答案：1是 0否',
               existing_comment='是否无答案1是0否',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('op_query_log', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='日志ID，主键',
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'op_eval_case',
        '评测集表：用于回归测试准确率/召回率',
        existing_comment='评测集表：质量回归',
        schema=None
    )
    op.alter_column('op_eval_case', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1启用 0禁用',
               existing_comment='1启用0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('op_eval_case', 'expected_doc_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='期望命中的文档ID',
               existing_comment='期望命中文档ID',
               existing_nullable=True)
    op.create_index(op.f('uk_llm_cost_date_model'), 'llm_cost_log', ['stat_date', 'model'], unique=True)
    op.create_table_comment(
        'kb_synonym',
        '同义词词典表：校内黑话/专有名词映射，提升召回',
        existing_comment='同义词词典表：提升召回',
        schema=None
    )
    op.drop_index(op.f('ix_kb_synonym_term'), table_name='kb_synonym')
    op.create_index(op.f('idx_term'), 'kb_synonym', ['term'], unique=False)
    op.alter_column('kb_synonym', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1启用 0禁用',
               existing_comment='1启用0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('kb_synonym', 'synonyms',
               existing_type=mysql.VARCHAR(length=512),
               comment='同义词/别名，逗号分隔，如 三方,就业协议书',
               existing_comment='同义词,逗号分隔',
               existing_nullable=False)
    op.alter_column('kb_synonym', 'term',
               existing_type=mysql.VARCHAR(length=128),
               comment='标准词，如 三方协议',
               existing_comment='标准词',
               existing_nullable=False)
    op.create_table_comment(
        'kb_index_task',
        '索引任务表：文档解析/入库异步任务监控',
        existing_comment='索引任务表：文档解析/入库任务监控',
        schema=None
    )
    op.drop_index(op.f('ix_kb_index_task_status'), table_name='kb_index_task')
    op.drop_index(op.f('ix_kb_index_task_document_id'), table_name='kb_index_task')
    op.create_index(op.f('idx_status'), 'kb_index_task', ['status'], unique=False)
    op.create_index(op.f('idx_document_id'), 'kb_index_task', ['document_id'], unique=False)
    op.alter_column('kb_index_task', 'progress',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='进度百分比 0-100',
               existing_comment='进度百分比0-100',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_index_task', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：0排队 1执行中 2成功 3失败',
               existing_comment='0排队1执行中2成功3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_index_task', 'task_type',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='任务类型：1解析 2向量化入库 3重建 4删除索引',
               existing_comment='1解析2入库3重建4删除索引',
               existing_nullable=False)
    op.alter_column('kb_index_task', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='任务ID，主键',
               existing_comment='任务ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('uk_kb_health_check_date'), 'kb_health_log', ['check_date'], unique=True)
    op.create_table_comment(
        'kb_faq',
        'FAQ问答对表：高频问题的标准答复',
        existing_comment='FAQ问答对表',
        schema=None
    )
    op.drop_index(op.f('ix_kb_faq_category_id'), table_name='kb_faq')
    op.create_index(op.f('idx_category_id'), 'kb_faq', ['category_id'], unique=False)
    op.create_index(op.f('ft_question'), 'kb_faq', ['question'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.alter_column('kb_faq', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态：1启用 0禁用',
               existing_comment='1启用0禁用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('kb_faq', 'hit_count',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='命中次数(热度统计)',
               existing_comment='命中次数(热度)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_faq', 'vector_id',
               existing_type=mysql.VARCHAR(length=128),
               comment='问题向量ID(用于相似问匹配)',
               existing_comment='问题向量ID',
               existing_nullable=True)
    op.alter_column('kb_faq', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='FAQ ID，主键',
               existing_comment='FAQ ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'kb_document_chunk',
        '文档分片表：切分后的文本块，含全文索引(ngram)支持关键词检索',
        existing_comment='文档分片表：切分文本块,含关键词全文索引',
        schema=None
    )
    op.drop_index(op.f('ix_kb_document_chunk_vector_id'), table_name='kb_document_chunk')
    op.drop_index(op.f('ix_kb_document_chunk_document_id'), table_name='kb_document_chunk')
    op.create_index(op.f('uk_doc_chunk'), 'kb_document_chunk', ['document_id', 'chunk_index'], unique=True)
    op.create_index(op.f('idx_vector_id'), 'kb_document_chunk', ['vector_id'], unique=False)
    op.create_index(op.f('ft_content'), 'kb_document_chunk', ['content'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.alter_column('kb_document_chunk', 'embedding_model',
               existing_type=mysql.VARCHAR(length=64),
               comment='生成向量所用模型名',
               existing_comment='生成向量的模型名',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'embedding',
               existing_type=mysql.JSON(),
               comment='向量备份(小规模可选存储,大规模留空)',
               existing_comment='向量备份(小规模可选)',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'vector_id',
               existing_type=mysql.VARCHAR(length=128),
               comment='向量库中的向量ID(外部引用)',
               existing_comment='向量库中的向量ID',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'page_no',
               existing_type=mysql.INTEGER(),
               comment='原文页码(便于溯源)',
               existing_comment='原文页码(溯源)',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'heading_path',
               existing_type=mysql.VARCHAR(length=512),
               comment='所属标题层级路径，如 第一章>第三条',
               existing_comment='标题层级路径',
               existing_nullable=True)
    op.alter_column('kb_document_chunk', 'chunk_index',
               existing_type=mysql.INTEGER(),
               comment='分片在文档内的序号(从0开始)',
               existing_comment='分片序号(从0开始)',
               existing_nullable=False)
    op.alter_column('kb_document_chunk', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='分片ID，主键',
               existing_comment='分片ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_kb_document_status'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_index_status'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_file_hash'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_effective_date'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_category_id'), table_name='kb_document')
    op.create_index(op.f('idx_status'), 'kb_document', ['status'], unique=False)
    op.create_index(op.f('idx_index_status'), 'kb_document', ['index_status'], unique=False)
    op.create_index(op.f('idx_file_hash'), 'kb_document', ['file_hash'], unique=False)
    op.create_index(op.f('idx_effective_date'), 'kb_document', ['effective_date'], unique=False)
    op.create_index(op.f('idx_category_id'), 'kb_document', ['category_id'], unique=False)
    op.alter_column('kb_document', 'status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='上架状态：1启用(可检索) 0下架',
               existing_comment='1上架可检索0下架',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('kb_document', 'index_status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='索引状态：0未索引 1索引中 2已索引 3失败',
               existing_comment='0未索引1索引中2已索引3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_document', 'parse_status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='解析状态：0待解析 1解析中 2成功 3失败',
               existing_comment='0待解析1解析中2成功3失败',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_document', 'confidential_level',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='密级：1公开 2校内 3受限',
               existing_comment='密级1公开2校内3受限',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('kb_document', 'expire_date',
               existing_type=sa.DATE(),
               comment='失效日期，为空表示长期有效',
               existing_comment='失效日期,空为长期有效',
               existing_nullable=True)
    op.alter_column('kb_document', 'effective_date',
               existing_type=sa.DATE(),
               comment='生效日期(用于过滤时效)',
               existing_comment='生效日期',
               existing_nullable=True)
    op.alter_column('kb_document', 'file_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment='文件内容哈希(SHA-256)，用于去重',
               existing_comment='内容哈希SHA-256,去重',
               existing_nullable=True)
    op.alter_column('kb_document', 'file_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='文件类型：pdf/docx/xlsx/txt/html',
               existing_comment='pdf/docx/xlsx/txt/html',
               existing_nullable=True)
    op.alter_column('kb_document', 'source_level',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='政策层级：1国家 2省 3市 4校级',
               existing_comment='政策层级1国2省3市4校',
               existing_nullable=True)
    op.alter_column('kb_document', 'source',
               existing_type=mysql.VARCHAR(length=255),
               comment='来源(发文机关/网站/上传人备注)',
               existing_comment='来源(发文机关/网站)',
               existing_nullable=True)
    op.alter_column('kb_document', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='文档ID，主键',
               existing_comment='文档ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_kb_category_parent_id'), table_name='kb_category')
    op.create_index(op.f('idx_parent_id'), 'kb_category', ['parent_id'], unique=False)
    op.alter_column('kb_category', 'sort',
               existing_type=mysql.INTEGER(),
               comment='排序值，越小越靠前',
               existing_comment='排序值,越小越靠前',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_category', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment='分类名称，如 就业政策/办事流程/招聘信息',
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('kb_category', 'parent_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='父分类ID，0为顶级',
               existing_comment='父分类ID,0为顶级',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('kb_category', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='分类ID，主键',
               existing_comment='分类ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('idx_fact_verify_message'), 'fact_verification_log', ['message_id'], unique=False)
    op.create_index(op.f('idx_consistency_message'), 'consistency_issue_log', ['message_id'], unique=False)
    op.create_index(op.f('idx_citation_quality_message'), 'citation_quality_log', ['message_id'], unique=False)
    op.create_index(op.f('idx_agent_refusal_created'), 'agent_refusal_log', ['created_at'], unique=False)
    op.alter_column('agent_refusal_log', 'query',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_comment='被拒答的用户问题',
               existing_nullable=False)
    op.create_table('embedding_cache',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('cache_key', mysql.VARCHAR(length=64), nullable=False, comment='SHA256(text|model|dim)'),
    sa.Column('text_sample', mysql.VARCHAR(length=200), nullable=True, comment='原文前200字(仅排查用)'),
    sa.Column('model', mysql.VARCHAR(length=64), nullable=False, comment='embedding模型名'),
    sa.Column('dim', mysql.INTEGER(), autoincrement=False, nullable=False, comment='向量维度'),
    sa.Column('embedding', mysql.LONGTEXT(), nullable=False, comment='向量本体(JSON字符串,精确往返)'),
    sa.Column('hit_count', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='命中次数'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='Embedding缓存L3持久层：Redis降级兜底',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Embedding缓存L3持久层：Redis降级兜底',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_embedding_cache_key'), 'embedding_cache', ['cache_key'], unique=True)
    op.drop_index(op.f('ix_user_favorite_user_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_message_id'), table_name='user_favorite')
    op.drop_table('user_favorite')
    op.drop_table('app_config')
    op.drop_table('announcement')
    # ### end Alembic commands ###
